### ISSUE TITLE
Move away from Poetry and Pipenv

### ISSUE THREAD

**Issue by bdsoha** [bdsoha/expycted#27]
Move away from the use of `Poetry` and `Pipenv` as part of the development workflow.
Such solutions are great, but the choice of a development work-belt should be that of the developer and not opinionated.

Instead, move to vanilla `Python`.
- [x] Replace `Poetry` in `pyproject.toml`
- [x] Migrate `Pipenv` into `pyproject.toml`
- [x] Add `[project.optional-dependencies]` for test and ci dependencies
- [x] Extract version using `dynamic = ["version"]` from a `__version__` variable
- [x] Update CI workflows
- [x] Update `.gitignore`

**Comment by petereon** [comment]
Up until now I didn't even realize I left both `pyproject.toml` and `Pipfile` in :sweat_smile:
