### ISSUE TITLE
Extend matchers and refactor

### ISSUE THREAD

**Issue by bdsoha** [bdsoha/expycted#7]
I would like to propose a few additions and refactors *(with your approval, I can begin working on them)*:

- [x] #11
- [x]  #18
- [x] #15 
- [x] #19 
- [x] #9

**Comment by petereon** [comment]
All, __1.__, __2.__ and __4.__ sound great, I have nothing to add there.
On 3rd point I have just few clarifying questions:
- `to_have_attributes()` is going to take a list of names of expected attributes as arguments?
- What is `to_almost_equal()` meaning to match? Numeric similarity with some sort of acceptable delta?

Your changes are very welcome!

**Comment by bdsoha** [comment]
Regarding `to_have_attributes`, I imaging the following overloaded signatures:
```python
def to_have_attribute(self, key: str):
    ...

def to_have_attribute(self, key: str, value: Any):
    ...

def to_have_attributes(self, *keys: str):
    ...
```

An explanation of [`to_almost_equal`](https://www.geeksforgeeks.org/python-unittest-assertalmostequal-function/) from the Python's built-in `unittest` package.

**Comment by petereon** [comment]
Both sound great! Looking forward to the PR(s)!

**Comment by bdsoha** [comment]
@petereon Before I get started, one more question, is there a reason why you split *alias* and *negated* test into separate methods?

**Example:**
- `test_to_contain_subfolder`
- `test_to_contain_subfolder_failing`
- `test_to_not_contain_subfolder`
- `test_to_not_contain_subfolder_failing`

**Comment by petereon** [comment]
@bdsoha Yes, it's for legacy reasons, there have previously been separate implementations for _negated_ matchers. Aliases don't necessarily make sense, I agree. As it is it would presumably make more sense to test just the `__init__` method that it _negates_ correctly.

**Comment by bdsoha** [comment]
@petereon I have an OOP proposition. 
Is there an alternative location were we can discuss the idea or do you want to continue here?
